github: [kim资源分享网, ]            # GitHub Sponsor 用户名（可填一个或多个）
patreon: kim资源分享网                        # Patreon 用户名
tidelift: cgj0123/kim-email-login             # Tidelift 上的 package 名称
custom: ["https://www.paypal.me/cgj1", https://blog.lekims.com/zz]  # 自定义赞助链接，如 PayPal、官网
